name: React app deployment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - run : npm i
      shell: bash
    - run : CI=false npx react-scripts build
      shell: bash
    - run : git config user.name github-actions
      shell: bash
    - run : git config user.email github-actions@github.com
      shell: bash
    - run : touch CNAME
      shell: bash
    - run : echo "akashchekka.com" > CNAME
      shell: bash
    - run : git --work-tree build add --all
      shell: bash
    - run : git --work-tree CNAME add
      shell: bash
    # - uses: 1arp/create-a-file-action@0.3
    #   with:
    #     path: ''
    #     file: 'CNAME'
    #     content: |
    #       akashchekka.com
    - run : git commit -m "Automatic Deploy action run by github-actions"
      shell: bash
    - run : git push origin HEAD:gh-pages --force
      shell: bash